# Generated by Django 2.2.16 on 2022-03-07 15:28

import reviews.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220307_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveIntegerField(default=1895, validators=[reviews.validators.validate_year]),
        ),
    ]
